name: Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/setup-cli@v2
      with:
        version: 'latest'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 024848477002.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t 024848477002.dkr.ecr.ap-south-1.amazonaws.com/my-flask-app:latest .

    - name: Push Docker image
      run: docker push 024848477002.dkr.ecr.ap-south-1.amazonaws.com/my-flask-app:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster default --service my-flask-app-service --force-new-deployment
